import csv, smtplib, ssl
port = 587 
smtp_server = "smtp.office365.com"
login = "justin@socialsafety.org" # paste your login generated by Mailtrap
password = "ElCortez2k" # paste your password generated by Mailtrap

message = """Subject: Your test score
To: {recipient}
From: {sender}

Hi {name}, thanks for accepting our challenge! Your current score is {score}. Contact us if you have further questions.
Cheers! """
sender = "justin@socialsafetyinitiative.org"

context=ssl.create_default_context()

with smtplib.SMTP(smtp_server, port) as server:
    server.connect(smtp_server,25)
    server.ehlo()
    server.starttls(context=context)
    server.ehlo()
    print(login)
    print(password)
    server.login(login, password)
    with open("mailmerge_database.csv") as file:
        reader = csv.reader(file)
        next(reader)  # add this to skip the header row
        print(reader)
        for email, name, score,recipient, sender in reader:
            server.sendmail(
               sender,
                email,
                message.format(name=name, recipient=email, sender=sender, score=score)
            )
            print(f'Sent to {name}')